version: "3.8"
services:
  server:
    build: ./server
    container_name: server_c
    ports:
      - '5000:5000'
      - '5001:5001'
      - '5002:5002'
      - '5003:5003'
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
  client:
    build: ./client
    container_name: client_c1
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    stdin_open: true
    depends_on:
      - server
